version: 2
updates:
  - package-ecosystem: npm #set the package ecosystem to npm
    directory: /api #looking in the api dir for the file
    schedule:
      interval: weekly #checking weekly for updates
      day: wednesday #checking on friday
    assignees: #assignes people to maintain the PR
      - VottonDev